URLS = {
    "Brandenburg":
        None,
    "Berlin":
        None,
    "Baden-Württemberg":
        None,
    "Bayern":
        None,
    "Bremen":
        None,
    "Hessen":
        None,
    "Hamburg":
        None,
    "Mecklenburg-Vorpommern":
        None,
    "Niedersachsen":
        None,
    "Nordrhein-Westfalen":
        "https://github.com/mundialis/openNRW/raw/master/dop/"
        "openNRW_DOP10_tileindex.gpkg.gz",
    "Rheinland-Pfalz":
        None,
    "Schleswig-Holstein":
        None,
    "Saarland":
        None,
    "Sachsen":
        None,
    "Sachsen-Anhalt":
        None
}
